In [2]:
import numpy as np
dataset_filename = "affinity_dataset.txt"
X = np.loadtxt(dataset_filename)
n_samples, n_features = X.shape
print("This dataset has {0} samples and {1} features".format(n_samples, n_features))

This dataset has 100 samples and 5 features


In [3]:
print(X[:5])

[[ 0.  0.  1.  1.  1.]
 [ 1.  1.  0.  1.  0.]
 [ 1.  0.  1.  1.  0.]
 [ 0.  0.  1.  1.  1.]
 [ 0.  1.  0.  0.  1.]]


In [4]:
# First, how many rows contain our premise: that a person is buying apples
num_apple_purchases = 0
for sample in X:
        if sample[3] == 1: #This person bought Apples
            num_apple_purchases += 1
print("{0} people bought Apples".format(num_apple_purchases))

36 people bought Apples


In [5]:
from collections import defaultdict
valid_rules = defaultdict(int)
invalid_rules =defaultdict(int)
num_occurances = defaultdict(int)

In [6]:
for sample in X:
    for premise in range(n_features):
        if sample[premise] == 0: 
            continue
        num_occurances[premise] += 1
        for conclusion in range(n_features):
            if premise == conclusion: 
                continue
            if sample[conclusion] == 1:
                valid_rules[(premise, conclusion)] += 1
            else:
                invalid_rules[(premise, conclusion)] += 1

In [7]:
support = valid_rules

In [8]:
# The names of the features, for your reference.
features = ["bread", "milk", "cheese", "apples", "bananas"]
confidence = defaultdict(float)
for premise, conclusion in valid_rules.keys():
    rule = (premise, conclusion)
    confidence[ rule] = valid_rules[rule] / num_occurances[premise]

In [9]:
def print_rule(premise, conclusion, support, confidence, features):
    premise_name = features[premise]
    conclusion_name = features[conclusion]
    print("Rule: If a person buys {0} they will also buy {1}".format(premise_name, conclusion_name))
    print(" - Support: {0}".format(support[(premise, conclusion)]))
    print(" - Confidence: {0:.3f}".format(confidence[(premise, conclusion)]))

In [10]:
premise = 1
conclusion = 3
print_rule(premise, conclusion, support, confidence, features)

Rule: If a person buys milk they will also buy apples
 - Support: 9
 - Confidence: 0.196


In [11]:
from operator import itemgetter
sorted_support = sorted(support.items(), key = itemgetter(1), reverse = True)

In [12]:
for index in range(5):
    print("Rule #{0}".format(index + 1))
    premise, conclusion = sorted_support[index][0]
    print_rule(premise, conclusion, support, confidence, features)

Rule #1
Rule: If a person buys cheese they will also buy bananas
 - Support: 27
 - Confidence: 0.659
Rule #2
Rule: If a person buys bananas they will also buy cheese
 - Support: 27
 - Confidence: 0.458
Rule #3
Rule: If a person buys cheese they will also buy apples
 - Support: 25
 - Confidence: 0.610
Rule #4
Rule: If a person buys apples they will also buy cheese
 - Support: 25
 - Confidence: 0.694
Rule #5
Rule: If a person buys apples they will also buy bananas
 - Support: 21
 - Confidence: 0.583
